# MySQL / MariaDB — tao database bang script trong resources/db/schema.sql
db.url=jdbc:mysql://localhost:3306/quanly_phong_tro?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
db.user=root
db.password=Ngocquy2501@
